name: virusscan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa
  - blast
  - repeatmasker
  - samtools
  - bamtools
  #- perl=5.32 # Locking the version helps prevent "BioPerl" version mismatches
#  - perl-bioperl 
  - coreutils
  - gawk
  - sed
  - grep
